## access.conf: Used for hiding "internal" nodes like the filter-chain
## This file will hide the audio filter nodes for all applications by setting
## specific permissions on them.

access.permission-managers = [
  {
    name = "steamos-default"
    default_permissions = "all"
    rules = [
      {
        matches = [
          { media.class = "Audio/Sink/Internal" }
          { media.class = "Audio/Source/Internal" }
          { media.class = "Stream/Input/Audio/Internal" }
          { media.class = "Stream/Output/Audio/Internal" }
          { node.name = "filter-chain-capture" }
          { node.name = "filter-chain-source" }
          {
            alsa.loopback = "true"
            media.class = "~Stream/*"
          }
          { node.create-loopback = "true" }
          { api.alsa.split.parent = "true" }
        ]
        actions = {
          set-permissions = ""
        }
      }
    ]
  }

  {
    name = "steamos-restricted"
    default_permissions = "rx"
    rules = [
      {
        matches = [
          { media.class = "Audio/Sink/Internal" }
          { media.class = "Audio/Source/Internal" }
          { media.class = "Stream/Input/Audio/Internal" }
          { media.class = "Stream/Output/Audio/Internal" }
          { node.name = "filter-chain-capture" }
          { node.name = "filter-chain-source" }
          {
            alsa.loopback = "true"
            media.class = "~Stream/*"
          }
          { node.create-loopback = "true" }
          { api.alsa.split.parent = "true" }
        ]
        actions = {
          set-permissions = ""
        }
      }
    ]
  }
]

access.rules = [
  {
    matches = [
      {
        access = "flatpak"
        media.category = "Manager"
      }
    ]
    actions = {
      update-props = {
        access = "flatpak-manager"
        permission_manager_name = "steamos-default"
      }
    }
  }

  {
    matches = [
      {
        access = "flatpak"
        media.category = "!\"Manager\""
      }
    ]
    actions = {
      update-props = {
        permission_manager_name = "steamos-restricted"
      }
    }
  }

  {
    matches = [
      {
        access = "restricted"
      }
    ]
    actions = {
      update-props = {
        permission_manager_name = "steamos-restricted"
      }
    }
  }

  {
    matches = [
      {
        access = "default"
        application.name = "!\"pipewire\""
      }
    ]
    actions = {
      update-props = {
        permission_manager_name = "steamos-default"
      }
    }
  }
]
