stages:          # List of stages for jobs, and their order of execution
  - build
  - test

default:
  tags:
    - docker
    - autoscaled

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential libboost-dev lv2-dev faust
  script:
    - make

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - make benchmark

