# This grants 'default' access to appliations connecting to the pipewire socket,
# and 'unrestricted' access to applications connecting to the manager socket.

module.access.args = {
    access.socket = { pipewire-0 = "restricted", pipewire-0-manager = "unrestricted" }
}

